name: tie_fp_dio
description: Extension to Dio Response
version: 1.0.0
homepage: https://github.com/unacorbatanegra/tie_fp_dio
issue_tracker: https://github.com/unacorbatanegra/tie_fp_dio/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1

  tie_fp: ^1.0.0

dev_dependencies:
  http_mock_adapter: ^0.4.4
  lints: ^2.0.1
  test: ^1.23.1
