name: tie_fp_dio
description: Extension to Dio Response
version: 0.0.1
homepage: https://github.com/unacorbatanegra/tie_fp_dio


environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.2.1+1
  
  flutter:
    sdk: flutter
  tie_fp: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

